### ISSUE TITLE
Leaky relu is slow due to constant checking of gpu() availability

### ISSUE THREAD

**Issue by iuliancioarca** [Ybakman/YoloV2#1]
First, please allow me to thank you for the effort of porting Yolo model to Julia!
I know this is work in progress, so please consider this "issue" more of an observation and not a bug.
I noticed that if I simply comment the "`if`" statement checking for gpu availability the execution time of "`displaytest`" function is reduced by 40% on my machine(from roughly 0.9s to 0.5s ,running on i5-6300u).

**Comment by Ybakman** [comment]
Thanks for the feedback! As I'm new in this topic (AI - ML), sometimes I couldn't figure out which part of the code causes slowness. So these type of advices are really important for me. I fixed the bug and removed the gpu checking part. Hopefully, it works fast both on cpu and gpu.

**Comment by iuliancioarca** [comment]
I'm also a beginner and most probably have even less experience than you (I find it awesome that you managed to port this code and it simply worked when I tried it). Please let me know if I can help you with some tasks( I can't promise I will be able to, but I'll try). Here is my email: iulian.cioarca@gmail.com

**Comment by Ybakman** [comment]
Currently, I'm working on how to train the weights. Also, I know this repo can be improved. For instance, I want to run the program on videos and improve efficiency by changing post-processing part maybe. So, your potential contribution can be very useful. I will keep in touch with you!  Thanks!
my mail: yavuzfarukbakman@hotmail.com
